### ISSUE TITLE
Determine why build command fails

### ISSUE THREAD

**Issue by mnriem** [manorrock/beehive#43]
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base@22/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base@22/java.lang.ProcessImpl.<init>(ProcessImpl.java:295)
	at java.base@22/java.lang.ProcessImpl.start(ProcessImpl.java:225)
	at java.base@22/java.lang.ProcessBuilder.start(ProcessBuilder.java:1126)

**Comment by mnriem** [comment]
Observations:

1. First command in the command array should be the executable to be used.
2. Executable must be in the current working directory if not using the full path.
3. A shell script should not be the first command in the command array.
